### PR TITLE
Adjusted things that weren't passing harness

### PR DESCRIPTION
**Pull request by sethverrill**
Adjusted methods, fixed tests, fixed spacing, fixed typos

### CODE REVIEW

**Comment by MiTOBrien** [comment]
Good work Seth

**Comment by sethverrill** [comment]
Fixed merge conflicts.

**Comment by BrodyNics77** [comment]
Looks good!

**Review by Jonathan-Atkins — APPROVED** [review]
no comment thanks for making these updates

**Comment by sethverrill** [comment]
Merging because I want to update my local

**Pull request merged**
